spring:
  application:
    name: notification
  kafka:
    topic: notifications
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      properties:
        specific.avro.reader: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:8081
    properties:
      schema.registry.url: http://localhost:8081
